import Head from "next/head";
import Styles from "../styles/Footer.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Wedcell</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className={Styles.privacy_policy}>
        <h1>Privacy Policy</h1>
        <p>
          Our management has created this Privacy Statement (Policy) in order to
          demonstrate our firm commitment to help our users better understand
          what information we collect about them and what may happen to that
          information.
        </p>
        <p>
          The terms "We, Wedcell, Us" refer to Wedcell.com and the terms "You,
          Your" refer to a user of Wedcell.com.
        </p>
        <p>
          In the course of our business of helping our viewers plan their
          wedding, we collect certain information from you.
        </p>
        <p>
          In the course of registering for and availing various services we
          provide from time to time through our website:Wedcell, you may be
          required to give your Name, address, Email address, phone number.
        </p>
        <p>
          The Personal Information is used for three general purposes: to
          customize the content you see, to fulfill your requests for certain
          services, and to contact you about our services. Unless otherwise
          stated explicitly, this Policy applies to Personal Information as
          disclosed on any of the Media.
        </p>
        <p>
          Dear Users, WEDCELL undertakes and acknowledges to be compliant with
          all necessary legal requirements and compliances and is under process
          of executing the GDPR regulations & compliances on its website  for
          all our relevant users. The Data we collect and use is upon your
          consent and none of our activities amount to breach of GDPR
          compliance. We value your security and privacy and are doing our best
          to ensure security of the data you provide to us in any manner
          whatsoever. We acknowledge your consent for providing such data to us
          for smooth execution of our services and note your acceptance to
          providing us with all information so collected, including Name,
          Gender, Email, Contact Number, Age, Location, Device Details, Browsing
          Information, SMS, App Install and Usage, Preferences, Intent etc.
        </p>
        <h4>Security</h4>
        <p>
          Personal Information will be kept confidential and we do not disclose
          the information except that in case you have specifically made an
          enquiry . Further, the vendors / advertisers who are listed with us,
          may call you, based on the query or enquiry that you make with us,
          enquiring about any Product / Service they might offer
        </p>
        <p>
          We will share Personal Information only under one or more of the
          following circumstances: - If we have your consent or deemed consent
          to do so - If we are compelled by law (including court orders) to do
          so.
        </p>
        <p>
          In furtherance of the confidentiality with which we treat Personal
          Information we have put in place appropriate physical, electronic, and
          managerial procedures to safeguard and secure the information we
          collect online.
        </p>
        <p>
          We give you the ability to edit your account information and
          preferences at any time, including whether you want us to contact you
          regarding any services. To protect your privacy and security, we will
          also take reasonable steps to verify your identity before granting
          access or making corrections.
        </p>
        <p>
          We treat data as an asset that must be protected against loss and
          unauthorized access. We employ many different security techniques to
          protect such data from unauthorized access by members inside and
          outside the company. However, "perfect security" does not exist on the
          Internet, or anywhere else in the world! You therefore agree that any
          security breaches beyond the control of our standard security
          procedures are at your sole risk and discretion.
        </p>
        <h4>Links to other Websites</h4>
        <p>
          We have affiliate links to many other online resources. We are not
          responsible for the practices employed by these affiliates or their
          websites linked to or from Wedcell.com nor the information or content
          contained on these third party websites. You should carefully review
          their privacy statements and other conditions of use and you agree you
          provide information or engage in transactions with these affiliates at
          your own risk.
        </p>
        <h4>Control Of Your Password</h4>
        <p>
          You are responsible for all actions taken with your login information
          and password, including fees. Therefore we do not recommend that you
          disclose your account password or login information to any third
          parties. If you lose control of your password, you may lose
          substantial control over your personally identifiable information and
          may be subject to legally binding actions taken on your behalf.
          Therefore, if your password has been compromised for any reason, you
          should immediately change your password
        </p>
        <h4>Content On The Site</h4>
        <p>
          Wedcell.com features some of the latest trends in Indian weddings
          around the world, and tries to give its users exposure to quality
          hand-picked content. In our endeavor, we feature pictures and stories
          from various real weddings and vendors. Vendors are expected to take
          utmost care to take permission / hold copyright of images given to us.
          We also feature weddings and articles where users have given us
          permission to use the same. However, in the unlikely event of anyone
          having any objection to content put up on our site, they are free to
          contact us immediately and we ll be happy to consider their request
          and take necessary action
        </p>
        <h4>Updates on Privacy Policy</h4>
        <p>
          We reserve the right to revise these Privacy Policies of Wedcell.com
          from time to time by updating this posting. Such revised policies will
          take effect as of the date of posting
        </p>
        <h4>Contact Us</h4>
        <p>
          If you have any further queries regarding the privacy policy, feel
          free to contact us at <b>info@wedcell.com</b> If you have any further
          queries regarding the privacy policy, feel free to contact us at{" "}
          <b>info@wedcell.com</b>
        </p>
        <h1>User Data Policy</h1>
        <h4>Data points collected for users:</h4>
        The following data points are being collected via the Facebook login
        process on our applications/website. These data points are
        <ul>
          <li>Name of the user</li>
          <li>Email address</li>
          <li>Contact number</li>
        </ul>
        <h4>Why do we need/use the above-mentioned data points:</h4>
        <ul>
          <li>
            In order to have access to all the features, benefits or Services on
            Our Platform: connecting with the vendors listed on our platform,
            wedding planning assistance. In short, to provide a seamless
            experience to our users, a user must first create an account on our
            Platform.
          </li>
          <li>
            In addition to the above basic data received from Facebook and other
            login methods, we also collect some additional optional data points
            for the user to avail of all the features, benefits or services on
            our platform. A user can choose to provide some additional personal
            information allowing others, including us, to identify the User:
            Name, Gender, Email, Contact Number, Age, Location, Device Details,
            Preferences etc.
          </li>
          <li>
            We do not store users’ credit card information for any in-app/
            website transaction to avail of any benefit or service. Reputed
            third party getaways are used to enable users to make such
            transactions. Only the user's email address is required and used as
            proof of payment confirmation.
          </li>
        </ul>
        <h4>In case of data deletions:</h4>
        <ul>
          <li>
            Users can request for deletion of data across all platforms.
            Requests for deletion can be sent via both{" "}
            <i>
              <b>android|IOS|</b>
            </i>{" "}
            applications. Alternatively, a user can write to us at{" "}
            <b>info@wedcell.com</b>
          </li>
        </ul>
      </div>
    </>
  );
}
